# Generated by Django 2.0.5 on 2018-06-02 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180602_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 21, 12, 31, 495558), verbose_name='发送时间'),
        ),
    ]
