# Generated by Django 2.0.5 on 2018-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180602_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRecord',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
