# Generated by Django 2.0.5 on 2018-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180603_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
