# Generated by Django 2.0.5 on 2018-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_in', models.FloatField(verbose_name='进水流量')),
                ('water_out', models.FloatField(verbose_name='出水流量')),
                ('COD', models.FloatField(verbose_name='出水COD')),
                ('BOD', models.FloatField(verbose_name='出水BOD')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Controler_threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_in', models.FloatField(verbose_name='进水流量')),
                ('water_out', models.FloatField(verbose_name='出水流量')),
                ('COD', models.FloatField(verbose_name='出水COD')),
                ('BOD', models.FloatField(verbose_name='出水BOD')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.FloatField(verbose_name='提升泵液位')),
                ('temperature', models.FloatField(verbose_name='曝气池温度')),
                ('PH', models.FloatField(verbose_name='曝气池PH')),
                ('density', models.FloatField(verbose_name='污泥浓度')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Processor_threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(verbose_name='提升泵液位')),
                ('temperature_min', models.FloatField(verbose_name='最低曝气池温度')),
                ('temperature_max', models.FloatField(verbose_name='最大曝气池温度')),
                ('PH_min', models.FloatField(verbose_name='最低曝气池PH')),
                ('PH_max', models.FloatField(verbose_name='最大曝气池PH')),
                ('density_min', models.FloatField(verbose_name='最低污泥浓度')),
                ('density_max', models.FloatField(verbose_name='最大污泥浓度')),
            ],
        ),
    ]
