# Generated by Django 2.0 on 2018-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20180627_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controler',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
